version: "3.9"

services:
  web:
    build: ./web
    container_name: politicia_web
    ports:
      - "8080:8080"         # mapeia a porta 8080 do host para o container
    environment:
      - FLASK_ENV=production
    networks:
      - politicia_net
    restart: always

networks:
  politicia_net:
    driver: bridge
